In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from backtester.data import load_prices

spy = load_prices('SPY', '2015-01-01', '2026-01-01')

Loaded SPY from cache: SPY_2015-01-01_2026-01-01.csv

In [9]:
spy.loc['2020-01-02'] # Access a specific date

Adj Close    2.953918e+02
Close        3.248700e+02
High         3.248900e+02
Low          3.225300e+02
Open         3.235400e+02
Volume       5.915120e+07
Name: 2020-01-02 00:00:00, dtype: float64

In [10]:
spy.loc['2020-01', 'Volume'] # Access a specific month and column

Date
2020-01-02     59151200
2020-01-03     77709700
2020-01-06     55653900
2020-01-07     40496400
2020-01-08     68296000
2020-01-09     48473300
2020-01-10     53029300
2020-01-13     47086800
2020-01-14     62832800
2020-01-15     72056600
2020-01-16     54050300
2020-01-17     95846000
2020-01-21     77742400
2020-01-22     48914900
2020-01-23     51963000
2020-01-24     87578400
2020-01-27     84062500
2020-01-28     63834000
2020-01-29     53888900
2020-01-30     75491800
2020-01-31    113845600
Name: Volume, dtype: int64

In [11]:
spy.loc['2020-01':'2020-06', ['Close', 'Adj Close']] # Access a range of dates and specific columns

                 Close   Adj Close
Date
2020-01-02  324.869995  295.391785
2020-01-03  322.410004  293.154968
2020-01-06  323.640015  294.273438
2020-01-07  322.730011  293.445923
2020-01-08  324.450012  295.009979
...                ...         ...
2020-06-24  304.089996  279.347046
2020-06-25  307.350006  282.341827
2020-06-26  300.049988  275.635834
2020-06-29  304.459991  279.687012
2020-06-30  308.359985  283.269592

[125 rows x 2 columns]

In [12]:
spy.iloc[0] # Access the first row

Adj Close    1.692675e+02
Close        2.054300e+02
High         2.068800e+02
Low          2.041800e+02
Open         2.063800e+02
Volume       1.214659e+08
Name: 2015-01-02 00:00:00, dtype: float64

In [13]:
spy.iloc[-1] # Access the last row

Adj Close    6.766350e+02
Close        6.819200e+02
High         6.873600e+02
Low          6.817100e+02
Open         6.871400e+02
Volume       7.414480e+07
Name: 2025-12-31 00:00:00, dtype: float64

In [14]:
spy.iloc[:5] # Access the first 5 rows

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2015-01-02,169.267487,205.429993,206.880005,204.179993,206.380005,121465900
2015-01-05,166.210632,201.720001,204.369995,201.350006,204.169998,169632600
2015-01-06,164.645035,199.820007,202.720001,198.860001,202.089996,209151400
2015-01-07,166.696732,202.309998,202.720001,200.880005,201.419998,125346700
2015-01-08,169.654739,205.899994,206.160004,203.990005,204.009995,147217800

In [17]:
spy.iloc[10:20] # Access rows from index 10 to 19

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2015-01-16,166.136475,201.630005,201.820007,198.550003,198.770004,211879600
2015-01-20,166.490753,202.059998,202.720001,200.169998,202.399994,130991100
2015-01-21,167.331192,203.080002,203.660004,200.940002,201.500000,122942700
2015-01-22,169.819595,206.100006,206.259995,202.330002,203.990005,174356000
2015-01-23,168.888458,204.970001,206.100006,204.809998,205.789993,117516800
2015-01-26,169.283997,205.449997,205.559998,203.850006,204.710007,92009700
2015-01-27,167.051056,202.740005,204.119995,201.740005,202.970001,134044600
2015-01-28,164.908752,200.139999,204.289993,199.910004,204.169998,168514300
2015-01-29,166.433060,201.990005,202.300003,198.679993,200.380005,173585400
2015-01-30,164.340225,199.449997,202.169998,199.130005,200.570007,197729700

In [18]:
spy.loc['2020-01-02':'2020-01-03'] # Access a range of dates

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2020-01-02,295.391785,324.869995,324.890015,322.529999,323.540009,59151200
2020-01-03,293.154968,322.410004,323.640015,321.100006,321.160004,77709700

In [19]:
prices = spy['Adj Close'].to_numpy() # Convert to numpy array

def double_with_loop(arr):
    result = []
    for p in arr:
        result.append(p * 2)
    return result

In [20]:
%timeit double_with_loop(prices)

212 μs ± 4.97 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [21]:
%timeit prices * 2

1.17 μs ± 10.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [25]:
prices > 500

array([False, False, False, ...,  True,  True,  True], shape=(2766,))

In [23]:
prices[prices > 500]

array([500.40438843, 500.91976929, 505.55303955, 507.22366333,
       506.262146  , 504.86334229, 503.93081665, 508.165802  ,
       508.06869507, 507.18481445, 503.96008301, 504.51367188,
       503.5617981 , 503.84341431, 504.42626953, 503.14413452,
       501.75512695, 502.30883789, 502.35733032, 505.25183105,
       505.90267944, 505.97064209, 508.29217529, 514.58636475,
       513.52746582, 514.26580811, 514.85821533, 516.12078857,
       514.63476562, 510.87582397, 514.25610352, 514.61529541,
       511.01184082, 507.62188721, 512.2454834 , 512.66308594,
       513.23614502, 519.33599854, 519.32641602, 518.69506836,
       520.29760742, 521.55078125, 525.83416748, 526.89294434,
       527.21350098, 531.40960693, 532.75964355, 531.3125    ,
       530.60003662, 528.87536621, 530.9119873 , 531.57458496,
       532.41253662, 530.31738281, 531.40887451, 534.98522949,
       537.37255859, 540.47131348, 541.09503174, 541.62115479,
       546.98059082, 542.26428223, 545.68457031, 547.18536377,
       550.43029785, 542.71258545, 538.54193115, 534.96563721,
       540.48114014, 539.63330078, 527.40386963, 524.65594482,
       530.53179932, 530.84368896, 528.1541748 , 536.73919678,
       529.1385498 , 519.28674316, 504.16314697, 508.81130981,
       505.41046143, 517.09417725, 519.37438965, 519.64727783,
       528.19317627, 529.85943604, 538.94134521, 540.14971924,
       545.31420898, 544.4276123 , 546.29852295, 542.01098633,
       547.7699585 , 546.4642334 , 547.21447754, 544.0378418 ,
       544.08654785, 549.28033447, 537.97680664, 536.87561035,
       535.56982422, 526.55603027, 532.45147705, 534.77075195,
       540.25683594, 544.80761719, 547.65301514, 548.46185303,
       548.68597412, 547.05871582, 556.3939209 , 555.43200684,
       556.82006836, 558.41326904, 557.18164062, 559.39068604,
       558.57940674, 560.81781006, 555.79376221, 556.02832031,
       555.01190186, 560.05535889, 554.99224854, 560.24108887,
       564.121521  , 563.13433838, 566.50653076, 571.13964844,
       566.70202637, 569.16522217, 569.21405029, 571.40356445,
       570.46520996, 570.16223145, 564.95239258, 566.17425537,
       565.97857666, 567.72839355, 568.6472168 , 566.92687988,
       555.81335449, 558.15911865, 556.95684814, 563.69146729,
       577.70806885, 582.17498779, 584.69677734, 585.25396729,
       583.43591309, 583.71929932, 579.96588135, 572.53735352,
       574.88323975, 576.98468018, 577.18017578, 580.27874756,
       582.07727051, 584.05163574, 587.10119629, 585.32226562,
       588.95825195, 590.01403809, 590.28771973, 593.95306396,
       592.97570801, 594.09979248, 591.04034424, 589.20269775,
       593.75762939, 590.69824219, 590.58099365, 593.1027832 ,
       590.65911865, 573.05541992, 572.8793335 , 579.76031494,
       583.2321167 , 589.71466064, 589.75390625, 583.54595947,
       576.88665771, 574.78796387, 573.37573242, 580.5447998 ,
       583.88916016, 577.28887939, 578.13226318, 569.3057251 ,
       570.18835449, 570.97296143, 581.35882568, 580.24078369,
       586.06634521, 591.43096924, 594.7557373 , 598.00189209,
       596.25628662, 587.82189941, 592.8727417 , 590.21484375,
       593.38262939, 590.22467041, 586.25274658, 590.18554688,
       592.57843018, 594.63800049, 589.19500732, 593.1963501 ,
       593.64746094, 591.73498535, 597.98223877, 597.95288086,
       599.70831299, 601.12060547, 598.61975098, 588.38092041,
       585.70355225, 582.79064941, 583.08502197, 573.77783203,
       582.73187256, 572.52246094, 565.74560547, 571.82611084,
       561.67559814, 564.82366943, 549.77935791, 545.20898438,
       548.10217285, 540.7956543 , 551.96624756, 556.22271729,
       550.21081543, 556.203125  , 554.59466553, 554.77758789,
       564.71289062, 566.0703125 , 559.31243896, 557.8270874 ,
       546.59338379, 550.26257324, 551.81671143, 555.30883789,
       527.94274902, 539.66833496, 516.02056885, 525.2277832 ,
       530.32330322, 528.83789062, 517.08282471, 517.82061768,
       505.49514771, 518.64697266, 526.68371582, 537.76977539,
       541.65539551, 541.86187744, 545.27526855, 545.49169922,
       549.35742188, 557.51226807, 554.31530762, 549.68218994,
       551.99389648, 555.83990479, 555.13183594, 573.47747803,
       577.26470947, 578.00244141, 580.82556152, 584.5045166 ,
       585.1439209 , 583.17651367, 573.34954834, 573.57580566,
       569.6607666 , 581.5043335 , 578.14013672, 580.42230225,
       579.77301025, 583.03887939, 586.36376953, 586.20629883,
       583.37329102, 589.36401367, 589.89508057, 593.23968506,
       591.54766846, 593.89874268, 587.2588501 , 592.84619141,
       587.7802124 , 587.69171143, 586.3114624 , 592.10272217,
       598.64385986, 598.97930908, 603.66552734, 606.66479492,
       609.56542969, 609.36810303, 612.13061523, 616.95495605,
       612.35742188, 612.02203369, 615.69219971, 617.42852783,
       615.25799561, 616.43212891, 613.7979126 , 615.84997559,
       619.61871338, 619.16491699, 620.33898926, 620.42773438,
       625.70605469, 625.91314697, 628.55725098, 628.39941406,
       626.74200439, 625.95263672, 623.60461426, 613.38354492,
       622.70672607, 619.54968262, 624.29522705, 623.77227783,
       628.63616943, 627.39306641, 634.07232666, 636.24285889,
       636.30200195, 634.81231689, 634.67407227, 631.23095703,
       629.55371094, 627.02813721, 636.65716553, 633.85528564,
       636.50915527, 637.95953369, 640.21875   , 636.4006958 ,
       631.68475342, 635.10827637, 640.41607666, 638.5612793 ,
       640.12994385, 641.60986328, 643.46466064, 648.81207275,
       648.59484863, 652.04797363, 651.15020752, 650.34118652,
       653.37988281, 656.61602783, 659.72247314, 656.13128662,
       654.04370117, 651.02630615, 654.75604248, 656.59625244,
       659.06951904, 661.31536865, 662.07702637, 662.06726074,
       664.44152832, 661.97814941, 665.92553711, 663.99633789,
       646.04998779, 655.9630127 , 655.16168213, 658.0703125 ,
       653.58862305, 657.29864502, 664.1348877 , 664.12493896,
       660.67224121, 664.58996582, 670.0213623 , 677.92614746,
       679.72662354, 680.05316162, 672.57385254, 674.7800293 ,
       676.04632568, 668.03277588, 670.34783936, 663.15545654,
       663.80834961, 674.16662598, 675.71002197, 676.08599854,
       664.86700439, 664.75805664, 658.56494141, 653.03460693,
       655.55743408, 645.56524658, 651.99584961, 661.59228516,
       667.81524658, 672.42547607, 676.0958252 , 673.00915527,
       674.25567627, 676.59051514, 677.08514404, 678.37127686,
       676.33325195, 675.74957275, 680.23126221, 681.81414795,
       674.48327637, 673.4642334 , 671.62408447, 664.23382568,
       669.24969482, 675.31536865, 679.52252197, 682.62817383,
       685.02947998, 684.96002197, 682.51904297, 681.68560791,
       676.63500977])

In [31]:
(prices > 500).sum()

np.int64(429)

In [44]:
manual_returns = (spy["Adj Close"] / spy["Adj Close"].shift(1)) - 1
manual_returns

Date
2015-01-02         NaN
2015-01-05   -0.018059
2015-01-06   -0.009419
2015-01-07    0.012461
2015-01-08    0.017745
                ...
2025-12-24    0.003518
2025-12-26   -0.000101
2025-12-29   -0.003564
2025-12-30   -0.001221
2025-12-31   -0.007409
Name: Adj Close, Length: 2766, dtype: float64

In [45]:
automatic_returns = spy["Adj Close"].pct_change()
automatic_returns

Date
2015-01-02         NaN
2015-01-05   -0.018059
2015-01-06   -0.009419
2015-01-07    0.012461
2015-01-08    0.017745
                ...
2025-12-24    0.003518
2025-12-26   -0.000101
2025-12-29   -0.003564
2025-12-30   -0.001221
2025-12-31   -0.007409
Name: Adj Close, Length: 2766, dtype: float64

In [50]:
manual_automatic_comparison = (manual_returns - automatic_returns).abs().max()
manual_automatic_comparison

np.float64(0.0)

In [59]:
automatic_returns.idxmin(), f"{automatic_returns.min():.2%}"

(Timestamp('2020-03-16 00:00:00'), '-10.94%')